[package]
name = "codedefender-api"
version = "0.1.0"
edition = "2024"

[dependencies]
codedefender-config = { path = "../config" }
reqwest = { version = "0.12.22", features = ["blocking"] }
serde = "1.0.219"
serde_json = "1.0.140"
